/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dekstop;

/**
 *
 * @author computer
 */
public class formtiketpesawat extends javax.swing.JFrame {

    /**
     * Creates new form formtiketpesawat
     */
    public formtiketpesawat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combomaskapai = new javax.swing.JComboBox<>();
        combokota = new javax.swing.JComboBox<>();
        combopaket = new javax.swing.JComboBox<>();
        txtbayar = new javax.swing.JTextField();
        labelBayar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Maskapai");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Kota Tujuan");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Jumlah Bayar");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Paket Perjalanan");

        combomaskapai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        combomaskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garuda Indonesia", "Batik Air" }));
        combomaskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomaskapaiActionPerformed(evt);
            }
        });

        combokota.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        combokota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semarang", "Yogyakarta" }));
        combokota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combokotaActionPerformed(evt);
            }
        });

        combopaket.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        combopaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1x", "PP" }));
        combopaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combopaketActionPerformed(evt);
            }
        });

        txtbayar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });

        labelBayar.setText("PESAN");
        labelBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelBayarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Form Pemesanan Tiket Pesawat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combomaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtbayar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combokota, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(combopaket, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(labelBayar)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combomaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combokota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combopaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(labelBayar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combomaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomaskapaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combomaskapaiActionPerformed

    private void labelBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelBayarActionPerformed

    float bayar     = 0;
    String maskapai = combomaskapai.getSelectedItem().toString();
    String kota     = combokota.getSelectedItem().toString();
    String paket    = combopaket.getSelectedItem().toString();
    
    if (maskapai.equalsIgnoreCase("Garuda Indonesia") && kota.equalsIgnoreCase("Semarang"))
        if (paket.equalsIgnoreCase("PP"))
            bayar=(750000-(750000*5/100))*2;
        else
            bayar=750000;
    
    else if (maskapai.equalsIgnoreCase("Garuda Indonesia") && kota.equalsIgnoreCase("Yogyakarta"))
        if (paket.equalsIgnoreCase("PP"))
            bayar=(450000-(450000*5/100))*2;
        else
            bayar=450000;
    
    else if (maskapai.equalsIgnoreCase("Batik Air") && kota.equalsIgnoreCase("Semarang"))
        if (paket.equalsIgnoreCase("PP"))
            bayar=(450000-(450000*5/100))*2;
        else
            bayar=450000;
    
    else if (maskapai.equalsIgnoreCase("Batik Air") && kota.equalsIgnoreCase("Yogyakarta"))
        if (paket.equalsIgnoreCase("PP"))
            bayar=(650000-(650000*5/100))*2;
        else
            bayar=650000;
    
    txtbayar.setText("Rp. "+String.valueOf(bayar));
    }//GEN-LAST:event_labelBayarActionPerformed

    private void combokotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combokotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combokotaActionPerformed

    private void combopaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combopaketActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formtiketpesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formtiketpesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formtiketpesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formtiketpesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formtiketpesawat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combokota;
    private javax.swing.JComboBox<String> combomaskapai;
    private javax.swing.JComboBox<String> combopaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton labelBayar;
    private javax.swing.JTextField txtbayar;
    // End of variables declaration//GEN-END:variables

}
